/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardDashboardImport } from './routes/dashboard/_dashboard'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()
const AuthSignupLazyImport = createFileRoute('/auth/signup')()
const AuthSigninLazyImport = createFileRoute('/auth/signin')()
const AuthOtpVerificationStepLazyImport = createFileRoute(
  '/auth/otp-verification-step',
)()
const AuthForgetPasswordLazyImport = createFileRoute('/auth/forget-password')()
const AuthCompleteForgetPasswordLazyImport = createFileRoute(
  '/auth/complete-forget-password',
)()
const AuthCompleteAccountInformationLazyImport = createFileRoute(
  '/auth/complete-account-information',
)()
const DashboardDashboardHomeLazyImport = createFileRoute(
  '/dashboard/_dashboard/Home',
)()
const DashboardDashboardFilesLazyImport = createFileRoute(
  '/dashboard/_dashboard/Files',
)()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupLazyRoute = AuthSignupLazyImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/signup.lazy').then((d) => d.Route))

const AuthSigninLazyRoute = AuthSigninLazyImport.update({
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/signin.lazy').then((d) => d.Route))

const AuthOtpVerificationStepLazyRoute =
  AuthOtpVerificationStepLazyImport.update({
    path: '/auth/otp-verification-step',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/auth/otp-verification-step.lazy').then((d) => d.Route),
  )

const AuthForgetPasswordLazyRoute = AuthForgetPasswordLazyImport.update({
  path: '/auth/forget-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/forget-password.lazy').then((d) => d.Route),
)

const AuthCompleteForgetPasswordLazyRoute =
  AuthCompleteForgetPasswordLazyImport.update({
    path: '/auth/complete-forget-password',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/auth/complete-forget-password.lazy').then((d) => d.Route),
  )

const AuthCompleteAccountInformationLazyRoute =
  AuthCompleteAccountInformationLazyImport.update({
    path: '/auth/complete-account-information',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/auth/complete-account-information.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardRoute = DashboardDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDashboardHomeLazyRoute = DashboardDashboardHomeLazyImport.update(
  {
    path: '/Home',
    getParentRoute: () => DashboardDashboardRoute,
  } as any,
).lazy(() =>
  import('./routes/dashboard/_dashboard.Home.lazy').then((d) => d.Route),
)

const DashboardDashboardFilesLazyRoute =
  DashboardDashboardFilesLazyImport.update({
    path: '/Files',
    getParentRoute: () => DashboardDashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboard.Files.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_dashboard': {
      id: '/dashboard/_dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/complete-account-information': {
      id: '/auth/complete-account-information'
      path: '/auth/complete-account-information'
      fullPath: '/auth/complete-account-information'
      preLoaderRoute: typeof AuthCompleteAccountInformationLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/complete-forget-password': {
      id: '/auth/complete-forget-password'
      path: '/auth/complete-forget-password'
      fullPath: '/auth/complete-forget-password'
      preLoaderRoute: typeof AuthCompleteForgetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/forget-password': {
      id: '/auth/forget-password'
      path: '/auth/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/otp-verification-step': {
      id: '/auth/otp-verification-step'
      path: '/auth/otp-verification-step'
      fullPath: '/auth/otp-verification-step'
      preLoaderRoute: typeof AuthOtpVerificationStepLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_dashboard/Files': {
      id: '/dashboard/_dashboard/Files'
      path: '/Files'
      fullPath: '/dashboard/Files'
      preLoaderRoute: typeof DashboardDashboardFilesLazyImport
      parentRoute: typeof DashboardDashboardImport
    }
    '/dashboard/_dashboard/Home': {
      id: '/dashboard/_dashboard/Home'
      path: '/Home'
      fullPath: '/dashboard/Home'
      preLoaderRoute: typeof DashboardDashboardHomeLazyImport
      parentRoute: typeof DashboardDashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  DashboardRoute: DashboardRoute.addChildren({
    DashboardDashboardRoute: DashboardDashboardRoute.addChildren({
      DashboardDashboardFilesLazyRoute,
      DashboardDashboardHomeLazyRoute,
    }),
  }),
  AuthCompleteAccountInformationLazyRoute,
  AuthCompleteForgetPasswordLazyRoute,
  AuthForgetPasswordLazyRoute,
  AuthOtpVerificationStepLazyRoute,
  AuthSigninLazyRoute,
  AuthSignupLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard",
        "/auth/complete-account-information",
        "/auth/complete-forget-password",
        "/auth/forget-password",
        "/auth/otp-verification-step",
        "/auth/signin",
        "/auth/signup"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_dashboard"
      ]
    },
    "/dashboard/_dashboard": {
      "filePath": "dashboard/_dashboard.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_dashboard/Files",
        "/dashboard/_dashboard/Home"
      ]
    },
    "/auth/complete-account-information": {
      "filePath": "auth/complete-account-information.lazy.tsx"
    },
    "/auth/complete-forget-password": {
      "filePath": "auth/complete-forget-password.lazy.tsx"
    },
    "/auth/forget-password": {
      "filePath": "auth/forget-password.lazy.tsx"
    },
    "/auth/otp-verification-step": {
      "filePath": "auth/otp-verification-step.lazy.tsx"
    },
    "/auth/signin": {
      "filePath": "auth/signin.lazy.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.lazy.tsx"
    },
    "/dashboard/_dashboard/Files": {
      "filePath": "dashboard/_dashboard.Files.lazy.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/Home": {
      "filePath": "dashboard/_dashboard.Home.lazy.tsx",
      "parent": "/dashboard/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
